version: '3.8'
services:
  pb-db:
    container_name: pokebook-backend
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pbdbbe
      POSTGRES_DB: pb-db
